In [1]:
# =========================================
# ✈️ Análisis de Datos Aeronáuticos
# Este proyecto tiene como objetivo analizar datos de aeropuertos para identificar patrones en el tráfico aéreo y comprender la estructura del sistema aeroportuario.

In [2]:
# =========================================
# 1. IMPORTACIÓN DE LIBRERÍAS
# =========================================
import pandas as pd

# =========================================
# 2. RUTA DE ARCHIVOS
# =========================================
ruta = r"C:\Users\ferna\Downloads\python\data\raw"

# =========================================
# 3. CARGA DE DATOS (CORREGIDO)
# =========================================

# Dataset vuelos (con separador correcto y manejo de errores)
df_vuelos = pd.read_csv(
    ruta + r"\aeropuertos_detalle.csv",
    encoding="latin1",
    sep=";",
    on_bad_lines="skip"
)

df_ministerio = pd.read_csv(
    ruta + r"\2020_informe_ministerio.csv",
    encoding="latin1",
    sep=";",
    on_bad_lines="skip",
    low_memory=False
)

print(df_ministerio.info())
print(df_vuelos.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212726 entries, 0 to 212725
Data columns (total 12 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   ï»¿Fecha                           212726 non-null  object
 1   Hora UTC                           212726 non-null  object
 2   Clase de Vuelo (todos los vuelos)  212726 non-null  object
 3   ClasificaciÃ³n Vuelo               212726 non-null  object
 4   Tipo de Movimiento                 212726 non-null  object
 5   Aeropuerto                         212726 non-null  object
 6   Origen / Destino                   212726 non-null  object
 7   Aerolinea Nombre                   212726 non-null  object
 8   Aeronave                           212726 non-null  object
 9   Pasajeros                          212726 non-null  int64
 10  PAX                                212726 non-null  int64
 11  Calidad dato                       212726 non-null  object
dtypes: int64(2), object(10)
memory usage: 19.5+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 693 entries, 0 to 692
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ï»¿local       693 non-null    object
 1   oaci           124 non-null    object
 2   iata           90 non-null     object
 3   tipo           693 non-null    object
 4   denominacion   693 non-null    object
 5   coordenadas    693 non-null    object
 6   latitud        693 non-null    float64
 7   longitud       693 non-null    float64
 8   elev           693 non-null    float64
 9   uom_elev       693 non-null    object
 10  ref            683 non-null    object
 11  distancia_ref  688 non-null    float64
 12  direccion_ref  679 non-null    object
 13  condicion      693 non-null    object
 14  control        693 non-null    object
 15  region         693 non-null    object
 16  fir            693 non-null    object
 17  uso            470 non-null    object
 18  trafico        693 non-null    object
 19  sna            693 non-null    object
 20  concesionado   693 non-null    object
 21  provincia      693 non-null    object
 22  inhab          693 non-null    object
dtypes: float64(4), object(19)
memory usage: 124.7+ KB
None

In [3]:
print(df_vuelos.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 693 entries, 0 to 692
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ï»¿local       693 non-null    object
 1   oaci           124 non-null    object
 2   iata           90 non-null     object
 3   tipo           693 non-null    object
 4   denominacion   693 non-null    object
 5   coordenadas    693 non-null    object
 6   latitud        693 non-null    float64
 7   longitud       693 non-null    float64
 8   elev           693 non-null    float64
 9   uom_elev       693 non-null    object
 10  ref            683 non-null    object
 11  distancia_ref  688 non-null    float64
 12  direccion_ref  679 non-null    object
 13  condicion      693 non-null    object
 14  control        693 non-null    object
 15  region         693 non-null    object
 16  fir            693 non-null    object
 17  uso            470 non-null    object
 18  trafico        693 non-null    object
 19  sna            693 non-null    object
 20  concesionado   693 non-null    object
 21  provincia      693 non-null    object
 22  inhab          693 non-null    object
dtypes: float64(4), object(19)
memory usage: 124.7+ KB
None

In [4]:
# 🧹 Limpieza de datos
#Se realiza el tratamiento de valores nulos, normalización de variables y corrección de inconsistencias.

In [5]:
# Limpiar nombres de columnas
df_vuelos.columns = df_vuelos.columns.str.replace("ï»¿", "")
df_ministerio.columns = df_ministerio.columns.str.replace("ï»¿", "")

# Pasar todo a minúsculas
df_vuelos.columns = df_vuelos.columns.str.lower()
df_ministerio.columns = df_ministerio.columns.str.lower()

# Eliminar espacios extra
df_vuelos.columns = df_vuelos.columns.str.strip()
df_ministerio.columns = df_ministerio.columns.str.strip()

# Renombrar columnas problemáticas manualmente
df_ministerio = df_ministerio.rename(columns={
    "clasificaciã³n vuelo": "clasificacion vuelo"
})

# Ver resultado
print(df_vuelos.columns)
print(df_ministerio.columns)

Index(['local', 'oaci', 'iata', 'tipo', 'denominacion', 'coordenadas',
       'latitud', 'longitud', 'elev', 'uom_elev', 'ref', 'distancia_ref',
       'direccion_ref', 'condicion', 'control', 'region', 'fir', 'uso',
       'trafico', 'sna', 'concesionado', 'provincia', 'inhab'],
      dtype='object')
Index(['fecha', 'hora utc', 'clase de vuelo (todos los vuelos)',
       'clasificacion vuelo', 'tipo de movimiento', 'aeropuerto',
       'origen / destino', 'aerolinea nombre', 'aeronave', 'pasajeros', 'pax',
       'calidad dato'],
      dtype='object')

In [6]:
## 🔄 Transformación de datos
# Se seleccionan variables relevantes y se preparan los datasets para el análisis.

In [7]:
#Se analizan distribuciones, relaciones entre variables y patrones relevantes en los datos.

# ===============================
# SELECCIÓN DATASET MINISTERIO
# ===============================

df_ministerio = df_ministerio[
    [
        "fecha",
        "hora utc",
        "clasificacion vuelo",
        "tipo de movimiento",
        "aeropuerto",
        "origen / destino",
        "aerolinea nombre",
        "pasajeros",
        "calidad dato"
    ]
]


# ===============================
# SELECCIÓN DATASET VUELOS
# ===============================

df_vuelos = df_vuelos[
    [
        "local",
        "oaci",
        "latitud",
        "longitud",
        "provincia",
        "tipo",
        "trafico"
    ]
]


# Verificar
print(df_ministerio.head())
print(df_vuelos.head())

      fecha hora utc clasificacion vuelo tipo de movimiento aeropuerto  \
0  1/1/2020    00:06       Internacional         Aterrizaje        EZE
1  1/1/2020    00:08       Internacional           Despegue        EZE
2  1/1/2020    00:10          DomÃ©stico         Aterrizaje        PAL
3  1/1/2020    00:13       Internacional           Despegue        EZE
4  1/1/2020    00:13          DomÃ©stico         Aterrizaje        PAL

  origen / destino                     aerolinea nombre  pasajeros  \
0             LEMD   IBERIA - LINEAS AÃREAS DE ESPAÃA        239
1             SCEL  LAN ARGENTINA S.A. (LATAM AIRLINES)        152
2              BAR               JETSMART AIRLINES S.A.        116
3             KDFW               AMERICAN AIRLINES INC.        255
4              DOZ               JETSMART AIRLINES S.A.        146

  calidad dato
0   DEFINITIVO
1   DEFINITIVO
2   DEFINITIVO
3   DEFINITIVO
4   DEFINITIVO
  local  oaci   latitud  longitud            provincia        tipo   trafico
0   ACB   NaN -60.57066 -33.27226            SANTA FÃ  AerÃ³dromo  Nacional
1   ACH   NaN -64.61351 -37.40164             LA PAMPA  AerÃ³dromo  Nacional
2   ACM   NaN -60.14170 -34.07574         BUENOS AIRES  AerÃ³dromo  Nacional
3   ADO  SAWD -65.90410 -47.73511           SANTA CRUZ  AerÃ³dromo  Nacional
4   ADT   NaN -62.26462 -28.85541  SANTIAGO DEL ESTERO  AerÃ³dromo  Nacional

In [8]:
## ⏱️ Ingeniería de variables
#Se generan nuevas variables como hora y franjas horarias para facilitar el análisis.

In [9]:
df_ministerio["fecha"] = pd.to_datetime(df_ministerio["fecha"], errors="coerce")
print(df_ministerio["fecha"].head())
print(df_ministerio["fecha"].dtype)

0   2020-01-01
1   2020-01-01
2   2020-01-01
3   2020-01-01
4   2020-01-01
Name: fecha, dtype: datetime64[ns]
datetime64[ns]

In [10]:
def limpiar_texto(texto):
    try:
        return texto.encode("latin1").decode("utf-8")
    except:
        return texto
# Seleccionar columnas de texto
columnas_texto = df_ministerio.select_dtypes(include="object").columns

# Aplicar limpieza
for col in columnas_texto:
    df_ministerio[col] = df_ministerio[col].apply(limpiar_texto)
print(df_ministerio.head())

       fecha hora utc clasificacion vuelo tipo de movimiento aeropuerto  \
0 2020-01-01    00:06       Internacional         Aterrizaje        EZE
1 2020-01-01    00:08       Internacional           Despegue        EZE
2 2020-01-01    00:10           Doméstico         Aterrizaje        PAL
3 2020-01-01    00:13       Internacional           Despegue        EZE
4 2020-01-01    00:13           Doméstico         Aterrizaje        PAL

  origen / destino                     aerolinea nombre  pasajeros  \
0             LEMD     IBERIA - LINEAS AÉREAS DE ESPAÑA        239
1             SCEL  LAN ARGENTINA S.A. (LATAM AIRLINES)        152
2              BAR               JETSMART AIRLINES S.A.        116
3             KDFW               AMERICAN AIRLINES INC.        255
4              DOZ               JETSMART AIRLINES S.A.        146

  calidad dato
0   DEFINITIVO
1   DEFINITIVO
2   DEFINITIVO
3   DEFINITIVO
4   DEFINITIVO

In [11]:
# Seleccionar columnas de texto en df_vuelos
columnas_texto_vuelos = df_vuelos.select_dtypes(include="object").columns

# Aplicar limpieza
for col in columnas_texto_vuelos:
    df_vuelos[col] = df_vuelos[col].apply(limpiar_texto)

# Ver resultado
print(df_vuelos.head())

  local  oaci   latitud  longitud            provincia       tipo   trafico
0   ACB   NaN -60.57066 -33.27226             SANTA FÉ  Aeródromo  Nacional
1   ACH   NaN -64.61351 -37.40164             LA PAMPA  Aeródromo  Nacional
2   ACM   NaN -60.14170 -34.07574         BUENOS AIRES  Aeródromo  Nacional
3   ADO  SAWD -65.90410 -47.73511           SANTA CRUZ  Aeródromo  Nacional
4   ADT   NaN -62.26462 -28.85541  SANTIAGO DEL ESTERO  Aeródromo  Nacional

In [12]:
df_ministerio["hora"] = pd.to_datetime(df_ministerio["hora utc"], errors="coerce").dt.hour
print(df_ministerio[["hora utc", "hora"]].head())

C:\Users\ferna\AppData\Local\Temp\ipykernel_8616\2985566456.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_ministerio["hora"] = pd.to_datetime(df_ministerio["hora utc"], errors="coerce").dt.hour

  hora utc  hora
0    00:06     0
1    00:08     0
2    00:10     0
3    00:13     0
4    00:13     0

In [13]:
df_ministerio["hora"] = pd.to_datetime(
    df_ministerio["hora utc"],
    format="%H:%M",
    errors="coerce"
).dt.hour
df_ministerio.head()

,fecha,hora utc,clasificacion vuelo,tipo de movimiento,aeropuerto,origen / destino,aerolinea nombre,pasajeros,calidad dato,hora
0,2020-01-01,00:06,Internacional,Aterrizaje,EZE,LEMD,IBERIA - LINEAS AÉREAS DE ESPAÑA,239,DEFINITIVO,0
1,2020-01-01,00:08,Internacional,Despegue,EZE,SCEL,LAN ARGENTINA S.A. (LATAM AIRLINES),152,DEFINITIVO,0
2,2020-01-01,00:10,Doméstico,Aterrizaje,PAL,BAR,JETSMART AIRLINES S.A.,116,DEFINITIVO,0
3,2020-01-01,00:13,Internacional,Despegue,EZE,KDFW,AMERICAN AIRLINES INC.,255,DEFINITIVO,0
4,2020-01-01,00:13,Doméstico,Aterrizaje,PAL,DOZ,JETSMART AIRLINES S.A.,146,DEFINITIVO,0

In [14]:

df_ministerio["hora"].value_counts().sort_index()

hora
0      6195
1      4613
2      3374
3      2019
4      1549
5      1537
6      1594
7      2750
8      3848
9      6626
10    10060
11    13239
12    15855
13    15938
14    15180
15    14680
16    13955
17    13494
18    12997
19    12186
20    11650
21    11337
22    10480
23     7570
Name: count, dtype: int64

In [15]:
df_ministerio["hora"].isnull().sum()

np.int64(0)

In [16]:
df_ministerio[
    df_ministerio["hora"].isnull()
][["hora utc"]]

Empty DataFrame
Columns: [hora utc]
Index: []

In [17]:
df_ministerio["franja_horaria"] = pd.cut(
    df_ministerio["hora"],
    bins=[0, 6, 12, 18, 24],
    labels=["Madrugada", "Mañana", "Tarde", "Noche"],
    right=False
)

In [18]:
## 🔗 Integración de datos
#Se combinan los datasets de vuelos y aeropuertos mediante un merge.

In [19]:
df_final = pd.merge(
    df_ministerio,
    df_vuelos,
    left_on="aeropuerto",
    right_on="local",
    how="left"
)

In [20]:
df_final.isnull().sum()

fecha                  124790
hora utc                    0
clasificacion vuelo         0
tipo de movimiento          0
aeropuerto                  0
origen / destino            0
aerolinea nombre            0
pasajeros                   0
calidad dato                0
hora                        0
franja_horaria              0
local                       0
oaci                        0
latitud                     0
longitud                    0
provincia                   0
tipo                        0
trafico                     0
dtype: int64

In [21]:
df_final = df_final.drop_duplicates()

In [22]:
df_final["provincia"] = df_final["provincia"].fillna("Desconocido")

In [23]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 194821 entries, 0 to 212725
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   fecha                87425 non-null   datetime64[ns]
 1   hora utc             194821 non-null  object
 2   clasificacion vuelo  194821 non-null  object
 3   tipo de movimiento   194821 non-null  object
 4   aeropuerto           194821 non-null  object
 5   origen / destino     194821 non-null  object
 6   aerolinea nombre     194821 non-null  object
 7   pasajeros            194821 non-null  int64
 8   calidad dato         194821 non-null  object
 9   hora                 194821 non-null  int32
 10  franja_horaria       194821 non-null  category
 11  local                194821 non-null  object
 12  oaci                 194821 non-null  object
 13  latitud              194821 non-null  float64
 14  longitud             194821 non-null  float64
 15  provincia            194821 non-null  object
 16  tipo                 194821 non-null  object
 17  trafico              194821 non-null  object
dtypes: category(1), datetime64[ns](1), float64(2), int32(1), int64(1), object(12)
memory usage: 26.2+ MB

In [24]:
## 📊 Análisis exploratorio
# Se analizan estadísticas descriptivas y distribución de los datos.

In [25]:
df_final.describe()

,fecha,pasajeros,hora,latitud,longitud
count,87425,194821.000000,194821.000000,194821.000000,194821.000000
mean,2020-06-21 15:40:37.458392832,54.872570,14.121111,-61.574230,-34.862614
min,2020-01-01 00:00:00,0.000000,0.000000,-72.053056,-54.843333
25%,2020-04-01 00:00:00,0.000000,11.000000,-65.270278,-34.822222
50%,2020-06-12 00:00:00,3.000000,15.000000,-58.643611,-34.558889
75%,2020-10-01 00:00:00,114.000000,19.000000,-58.535833,-32.903611
max,2020-12-12 00:00:00,475.000000,23.000000,-54.473540,-24.392500
std,NaN,71.483615,5.799306,4.409921,5.409463

In [26]:
df_final = df_final[df_final["pasajeros"] >= 0]

In [27]:
print("DF VUELOS:")
print(df_vuelos.head())

print("\nDF MINISTERIO:")
print(df_ministerio.head())

DF VUELOS:
  local  oaci   latitud  longitud            provincia       tipo   trafico
0   ACB   NaN -60.57066 -33.27226             SANTA FÉ  Aeródromo  Nacional
1   ACH   NaN -64.61351 -37.40164             LA PAMPA  Aeródromo  Nacional
2   ACM   NaN -60.14170 -34.07574         BUENOS AIRES  Aeródromo  Nacional
3   ADO  SAWD -65.90410 -47.73511           SANTA CRUZ  Aeródromo  Nacional
4   ADT   NaN -62.26462 -28.85541  SANTIAGO DEL ESTERO  Aeródromo  Nacional

DF MINISTERIO:
       fecha hora utc clasificacion vuelo tipo de movimiento aeropuerto  \
0 2020-01-01    00:06       Internacional         Aterrizaje        EZE
1 2020-01-01    00:08       Internacional           Despegue        EZE
2 2020-01-01    00:10           Doméstico         Aterrizaje        PAL
3 2020-01-01    00:13       Internacional           Despegue        EZE
4 2020-01-01    00:13           Doméstico         Aterrizaje        PAL

  origen / destino                     aerolinea nombre  pasajeros  \
0             LEMD     IBERIA - LINEAS AÉREAS DE ESPAÑA        239
1             SCEL  LAN ARGENTINA S.A. (LATAM AIRLINES)        152
2              BAR               JETSMART AIRLINES S.A.        116
3             KDFW               AMERICAN AIRLINES INC.        255
4              DOZ               JETSMART AIRLINES S.A.        146

  calidad dato  hora franja_horaria
0   DEFINITIVO     0      Madrugada
1   DEFINITIVO     0      Madrugada
2   DEFINITIVO     0      Madrugada
3   DEFINITIVO     0      Madrugada
4   DEFINITIVO     0      Madrugada

In [28]:
df_final["clasificacion vuelo"] = df_final["clasificacion vuelo"].replace({
    "Dom": "Doméstico",
    "Inter": "Internacional"
})

In [29]:
## 📈 Análisis de pasajeros por provincia
# Se agrupan los datos para analizar la cantidad de pasajeros por provincia y tipo de vuelo.

In [30]:
df_pivot = df_final.pivot_table(
    index="provincia",
    columns="clasificacion vuelo",
    values="pasajeros",
    aggfunc="sum",
    fill_value=0
)

print(df_pivot.head())

clasificacion vuelo              Doméstico  Internacional
provincia
BUENOS AIRES                       1079311        2943471
CATAMARCA                            11421           1222
CHACO                                49927            437
CHUBUT                              250287            109
CIUDAD AUTÓNOMA DE BUENOS AIRES    2247440          76019

In [31]:
df_unpivot = df_pivot.reset_index().melt(
    id_vars="provincia",
    var_name="tipo_vuelo",
    value_name="pasajeros"
)

print(df_unpivot.head())

                         provincia tipo_vuelo  pasajeros
0                     BUENOS AIRES  Doméstico    1079311
1                        CATAMARCA  Doméstico      11421
2                            CHACO  Doméstico      49927
3                           CHUBUT  Doméstico     250287
4  CIUDAD AUTÓNOMA DE BUENOS AIRES  Doméstico    2247440

In [32]:
print(df_unpivot.info())
print(df_unpivot.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   provincia   48 non-null     object
 1   tipo_vuelo  48 non-null     object
 2   pasajeros   48 non-null     int64
dtypes: int64(1), object(2)
memory usage: 1.3+ KB
None
          pasajeros
count  4.800000e+01
mean   2.227152e+05
std    5.449864e+05
min    0.000000e+00
25%    5.202500e+02
50%    1.834050e+04
75%    2.055742e+05
max    2.943471e+06

In [33]:
df_unpivot.to_csv(
    r"C:\Users\ferna\Downloads\python\data\processed\pasajeros_por_provincia.csv",
    index=False,
    encoding="utf-8"
)

In [34]:
import os

print(os.listdir(r"C:\Users\ferna\Downloads\python\data\processed"))

['aeropuertos_limpio.csv', 'normalizacion_pasajeros.csv', 'pasajeros_por_provincia.csv']

In [35]:
## 🧠 Conclusiones

#- El tráfico aéreo se concentra principalmente en ciertas provincias como Buenos Aires
#- Existe una diferencia significativa entre vuelos domésticos e internacionales
#- La limpieza de datos es clave para obtener resultados confiables